name: 🐞 New Bug Report
description: Create a bug report
title: "🐞[Bug]: "
labels: [Bug]
assignees: "David-Maisonave"
body:
  - type: markdown
    attributes:
      value: |
       Thank you for taking the time to fill out this bug report!
       Fields marked with an asterisk (*) are required, and remaining fields are optional, but we encourage their usage.
  - type: textarea
    id: feature
    attributes:
      label: Please enter a clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: What Operating System (OS)?
      placeholder: e.g. Windows, MacOS, Linux, Any
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: What version of MediaFileDuplicateFinder?
      placeholder: e.g. 1.0, 1.1
    validations:
      required: true
  - type: input
    id: app-download
    attributes:
      label: Where did you download MediaFileDuplicateFinder from?
      placeholder: e.g. github, sourceforge.net, Axter.com etc.
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: What are the steps used to reproduce this issue?
    validations:
      required: false      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What was the expected behavior?
    validations:
      required: false      
  - type: textarea
    id: snapshots
    attributes:
      label: Snapshot(s)
      description: Optionally attach snapshot(s) which displays the bug.
    validations:
      required: false      
