name: 🐞 New Bug Report
description: Create a bug report
title: "🐞[Bug]: "
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
       Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: feature
    attributes:
      label: A clear and concise description of the bug
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: In what Operating System did the bug occur?
      placeholder: e.g. Windows, MacOS, Linux
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: What version of MediaFileDuplicateFinder?
      placeholder: e.g. 1.0, 1.1
    validations:
      required: true
  - type: input
    id: app-download
    attributes:
      label: Where did you download MediaFileDuplicateFinder from?
      placeholder: e.g. github, sourceforge.net, Axter.com etc.
    validations:
      required: false
  - type: textarea
    id: Snapshots
    attributes:
      label: Snapshot(s)
      description: Optionally attach snapshot(s) which displays the bug.
    validations:
      required: false      
