name: Feature Request UI
description: Suggest an idea to improve MediaFileDuplicateFinder
title: "[Enhancement_UI]: "
labels: [Enhancement, GUI]
body:
  - type: markdown
    attributes:
      value: |
       Please fill out the following fields with as much detail as possible:
  - type: textarea
    id: feature
    attributes:
      label: A clear and concise description of the feature or enhancement you'd like to see in MediaFileDuplicateFinder
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Is it OS specific?
      placeholder: e.g. Windows, MacOS, Linux
    validations:
      required: false
  - type: input
    id: hb-download
    attributes:
      label: Where did you download MediaFileDuplicateFinder from?
      placeholder: e.g. github, sourceforge.net, Axter.com etc.
    validations:
      required: false
  - type: textarea
    id: Snapshots
    attributes:
      label: Snapshots / Images
      description: Optionally attach images which can help explain the feature, and a description of what to look for in the image(s).
    validations:
      required: false      
